'''
Diana Cecilia Martinez Valverde
Jose Bernardo Giron Arana
'''

import string
BeeError = 'TypeError'

#int - float - string

semanticCube = {
    ##  ##  ##  ##  ##  ##  ##  ## op1 INT ##  ##  ##  ##  ##  ##  ##  ##
    'int' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : 'int',
            'v.y' : 'int',
            'int' : 'int',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'int',
            'r.g' : 'int',
            'r.b' : 'int',
            'r.a' : 'int',
            's' : BeeError,
        },
        '-': {
            'v' : BeeError,
            'v.x' : 'int',
            'v.y' : 'int',
            'int' : 'int',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'int',
            'r.g' : 'int',
            'r.b' : 'int',
            'r.a' : 'int',
            's' : BeeError,
        },
        '*': {
            'v' : BeeError,
            'v.x' : 'int',
            'v.y' : 'int',
            'int' : 'int',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'int',
            'r.g' : 'int',
            'r.b' : 'int',
            'r.a' : 'int',
            's' : BeeError,
        },
        '/': {
            'v' : BeeError,
            'v.x' : 'int',
            'v.y' : 'int',
            'int' : 'int',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'int',
            'r.g' : 'int',
            'r.b' : 'int',
            'r.a' : 'int',
            's' : BeeError,
        },
        '==': {
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>': {
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## 🎈  op1 FLOAT 🎈 ##  ##  ##  ##  ##  ##  ##  ##
    'f' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : 'v',
            'v.y' : 'v',
            'int' : 'f',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : BeeError,
            'v.x' : 'v',
            'v.y' : 'v',
            'int' : 'f',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : BeeError,
            'v.x' : 'v',
            'v.y' : 'v',
            'int' : 'f',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : BeeError,
            'v.x' : 'v',
            'v.y' : 'v',
            'int' : 'f',    
            'f' : 'f',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<': {
            # op 2
             'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&':{
            'v' : BeeError,
            'v.x' : 'b',
            'v.y' : 'b',
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## 🅱 op1 b 🅱 ##  ##  ##  ##  ##  ##  ##  ##
    'b' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '-': {
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '*': {
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '/': {
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '==': {
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : 'b',
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>': {
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<':{
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>=':{
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<=':{
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '!=':{
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : 'b',
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '||':{
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : 'b',
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '&&':{
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : 'b',
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## op1 VECTOR ##  ##  ##  ##  ##  ##  ##  ##
    'v' : {
        # operator
        '+': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : BeeError,    
            'r' : BeeError,
            'f' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : BeeError,   
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : BeeError,  
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : BeeError,   
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## ❌ op1 VECTOR X ATTR ❌ ##  ##  ##  ##  ##  ##  ##  ##
    'v.x' : {
        # operator
        '+': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : 'v',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : 'v',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : 'v',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : 'v',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',
            'f' : 'b',    
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',  
            'f' : 'b',  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',    
            'f' : 'b',
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b',   
            'f' : 'b', 
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b', 
            'f' : 'b',   
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b', 
            'f' : 'b',   
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : 'b', 
            'f' : 'b',   
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## ☯ op1 VECTOR Y ATTR ☯ ##  ##  ##  ##  ##  ##  ##  ##
    'v.y' : {
        # operator
        '+': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : 'v',
            'v.x' : 'v',
            'v.y' : 'v' ,
            'int' : 'v',    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError,
            'f' : BeeError,    
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError,  
            'f' : BeeError,  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError,  
            'f' : BeeError,  
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError,    
            'f' : BeeError,
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError,   
            'f' : BeeError, 
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : 'b',
            'v.x' : 'b',
            'v.y' : 'b' ,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : BeeError,
            'b' : BeeError,
            'r.r' : BeeError,
            'r.g' : BeeError,
            'r.b' : BeeError,
            'r.a' : BeeError,
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## 🏳‍🌈 op1 RGBA 🏳‍🌈 ##  ##  ##  ##  ##  ##  ##  ##
    'r' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'v',
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'v',
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'v',
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'v',
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,  
            'f' : BeeError,  
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError,  
            'f' : BeeError,  
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : BeeError, 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## 💖 op1 RGBA 💖 RED ATTR ##  ##  ##  ##  ##  ##  ##  ##
    'r.r' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',   
            'f' : BeeError, 
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',  
            'f' : BeeError,  
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## 🐲 op1 RGBA GREEN ATTR 🐲 ##  ##  ##  ##  ##  ##  ##  ##
    'r.g' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',   
            'f' : BeeError, 
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',  
            'f' : BeeError,  
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## 🐬 op1 RGBA BLUE ATTR 🐬 ##  ##  ##  ##  ##  ##  ##  ##
    'r.b' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',   
            'f' : BeeError, 
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',  
            'f' : BeeError,  
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
    ##  ##  ##  ##  ##  ##  ##  ## op1 👻 RGBA ALPHA ATTR 👻 ##  ##  ##  ##  ##  ##  ##  ##
    'r.a' : {
        # operator
        '+': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '-': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '*': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '/': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'r',  
            'f' : BeeError,  
            'r' : 'r',
            'b' : BeeError,
            'r.r' : 'r',
            'r.g' : 'r',
            'r.b' : 'r',
            'r.a' : 'r',
            's' : BeeError,
        },
        '>': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',   
            'f' : BeeError, 
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '<=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '>=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',  
            'f' : BeeError,  
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '==': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b',
            'f' : BeeError,    
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '!=': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '||': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
        '&&': {
            # op 2
            'v' : BeeError,
            'v.x' : BeeError,
            'v.y' : BeeError,
            'int' : 'b', 
            'f' : BeeError,   
            'r' : 'b',
            'b' : BeeError,
            'r.r' : 'b',
            'r.g' : 'b',
            'r.b' : 'b',
            'r.a' : 'b',
            's' : BeeError,
        },
    },
}

def sem(oper1, oper2, operator):

    return semanticCube[oper1][operator][oper2]
